#Travis CI configuration for KWIVER
# See http://travis-ci.org/Kitware/kwiver/

sudo: false

language: cpp

matrix:
  include:
    - compiler: gcc
      env:
        - C_COMPILER=gcc-4.8
        - CXX_COMPILER=g++-4.8
    - compiler: clang
      env: # default clang is version 3.4
        - C_COMPILER=clang
        - CXX_COMPILER=clang++

cache:
  directories:
  - $HOME/deps
  - /opt/fletch

before_script:
  - bash .travis/install-deps.sh

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libproj-dev
    - libgl1-mesa-dev
    - libxt-dev
    - libqt4-dev
    - libatlas-base-dev
    - python2.7-dev

script:
  - export PATH=$HOME/deps/bin:$PATH
  - mkdir build
  - cd build
  - cmake -DCMAKE_C_COMPILER=$C_COMPILER
          -DCMAKE_CXX_COMPILER=$CXX_COMPILER
          -DCMAKE_INSTALL_PREFIX=$HOME/install
          -Dfletch_DIR=/opt/fletch
          -DKWIVER_ENABLE_ARROWS=ON
          -DKWIVER_ENABLE_CERES=ON
          -DKWIVER_ENABLE_C_BINDINGS=ON
          -DKWIVER_ENABLE_DOCS=OFF
          -DKWIVER_ENABLE_LOG4CXX=OFF
          -DKWIVER_ENABLE_LOG4CPLUS=ON
          -DKWIVER_ENABLE_OPENCV=ON
          -DKWIVER_ENABLE_PROJ=ON
          -DKWIVER_ENABLE_PROCESSES=ON
          -DKWIVER_ENABLE_PYTHON=OFF
          -DKWIVER_ENABLE_SPROKIT=ON
          -DKWIVER_ENABLE_TESTS=ON
          -DKWIVER_ENABLE_TOOLS=ON
          -DKWIVER_ENABLE_TRACK_ORACLE=ON
          -DKWIVER_ENABLE_VISCL=OFF
          -DKWIVER_ENABLE_VXL=ON
          -DKWIVER_USE_BUILD_TREE=ON
          ../
  - make -j2
  - make install
  - ctest
